# Generated by Django 5.1.7 on 2025-03-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255, null=True)),
                ('job_description', models.CharField(max_length=255, null=True)),
                ('qualification', models.CharField(max_length=255, null=True)),
                ('skills', models.CharField(max_length=255, null=True)),
                ('salary', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='emplayee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('phon_number', models.IntegerField(null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploaded_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
