# Generated by Django 5.1.7 on 2025-04-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_finder_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emplayee',
            name='applied_job',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
