# Generated by Django 5.1.7 on 2025-04-01 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_finder_app', '0002_emplayee_applied_job'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='jobs',
        ),
    ]
