# Generated by Django 5.1.7 on 2025-04-01 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_finder_app', '0003_rename_admin_jobs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jobs',
            new_name='job',
        ),
    ]
