# Generated by Django 5.1.7 on 2025-04-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_finder_app', '0004_rename_jobs_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrename', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('password1', models.CharField(max_length=255, null=True)),
                ('password2', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
