# Generated by Django 5.1.7 on 2025-04-02 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_finder_app', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
