# Generated by Django 5.1.7 on 2025-04-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_finder_app', '0007_sign'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
